Rename examples folder so it's not counted as a source file
Otherwise, it breaks the build:

```text
vendor/github.com/Sirupsen/logrus/examples/hook/hook.go:12: cannot use airbrake.NewHook(123, "xyz", "development") (type *airbrake.airbrakeHook) as type "github.com/rafecolton/docker-builder/vendor/github.com/Sirupsen/logrus".Hook in argument to log.Hooks.Add:
        *airbrake.airbrakeHook does not implement "github.com/rafecolton/docker-builder/vendor/github.com/Sirupsen/logrus".Hook (wrong type for Fire method)
                have Fire(*"github.com/sirupsen/logrus".Entry) error
                want Fire(*"github.com/rafecolton/docker-builder/vendor/github.com/Sirupsen/logrus".Entry) error
```