hooks/syslog: skip tests on tinygo
TinyGo currently (v0.41.1) doesn't support `log/syslog`;
https://tinygo.org/docs/reference/lang-support/stdlib/#logsyslog

Don't exclude the whole package with build-tags as support may be
added in newer versions, but skip the test.

> The compiler gave the following error when running the tests for this package:
>
>     FAIL	log/syslog	0.000s
>     # log/syslog
>     /home/ron/.gvm/go/src/log/syslog/syslog_test.go:35:21: oe.Temporary undefined (type *net.OpError has no field or method Temporary)
>     /home/ron/.gvm/go/src/log/syslog/syslog_test.go:110:15: undefined: net.ListenPacket

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>