golangci-lint: silence errors
```
WARN [runner/nolint_filter] Found unknown linters in //nolint directives: scopelint
entry.go:44:6: the methods of "Entry" use pointer receiver and non-pointer receiver. (recvcheck)
type Entry struct {
     ^
logrus.go:13:6: the methods of "Level" use pointer receiver and non-pointer receiver. (recvcheck)
type Level uint32
     ^
internal/testutils/testutils.go:10:2: ST1001: should not use dot imports (staticcheck)
        . "github.com/sirupsen/logrus"
        ^
text_formatter.go:309:6: QF1001: could apply De Morgan's law (staticcheck)
                if !((ch >= 'a' && ch <= 'z') ||
                   ^
text_formatter.go:337:3: QF1012: Use fmt.Fprintf(...) instead of WriteString(fmt.Sprintf(...)) (staticcheck)
                b.WriteString(fmt.Sprintf("%q", stringVal))
                ^
internal/testutils/testutils.go:26:2: error-nil: use require.NoError (testifylint)
        require.Nil(t, err)
        ^
6 issues:
* recvcheck: 2
* staticcheck: 3
* testifylint: 1
```

Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>